name: print_debug
description: A flutter package to avoid printing in release mode
version: 1.0.0
author: Foyez Ahmed
homepage: hellonishad.com
repository: https://github.com/nisadrahman/debug-print-flutter-package

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
